# Dependabot configuration

version: 2
updates:
  # Enable version updates for javascript
  - package-ecosystem: "npm"
    # Look for `package.json/requirements.txt` and/or `lock` files in the `root` directory
    directory: "/"
    # Limit amount of open PRs
    open-pull-requests-limit: 5

    target-branch: "master"

    pull-request-branch-name:
      separator: "_"

    # Check the registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
